### ISSUE TITLE
What users usually use with cordova/ionic? Systemjs or webpack?

### ISSUE THREAD

**Issue by pleerock** [typeorm/cordova-example#2]
I guess webpack since its more popular?

**Comment by daniel-lang** [comment]
with ionic definitely webpack since the build chain is already setup for it. With cordova you can use whatever you want

**Comment by pleerock** [comment]
when we gonna have ionic example repo?) Im planning to release 0.1.0 very soon and we must have it

**Comment by daniel-lang** [comment]
Well I can create it anytime but for now I haven't found a way get it working other than changing the `.tsconfig.json`. If you want a example with that "hack", I can create one

**Comment by daniel-lang** [comment]
I going to close this now as the Ionic example is up and this example now uses webpack
